### ISSUE TITLE
EEPROM driver and demo does not work

### ISSUE THREAD

**Issue by kammce** [SJSU-Dev2/SJSU-Dev2#1034]
I get the following output from telemetry

![image](https://user-images.githubusercontent.com/4549768/72440939-9f763880-375e-11ea-8c88-b5b055d271cc.png)

Further down you see this though:

![image](https://user-images.githubusercontent.com/4549768/72440983-b4eb6280-375e-11ea-8234-ebaf8c13468c.png)

So it seems that the addressing is not correct.

**Comment by harmandersihra** [comment]
Just submitted a PR for this issue.

**Comment by kammce** [comment]
Resolved by #1304
