### ISSUE TITLE
Not sure what this is supposed to say, but it seems like a typo

### ISSUE THREAD

**Issue by harmandersihra** [SJSU-Dev2/SJSU-Dev2#1324]
https://github.com/SJSU-Dev2/SJSU-Dev2/blob/566011b472e44cc7e589dd367eccba449d8ea8b0/library/L1_Peripheral/lpc40xx/gpio.hpp#L184

**Comment by kammce** [comment]
Yeah, thats about correct, but remove we need to remove the random "a" at the end and put a period. Can you fix this @harmandersihra ?
